Agent release 2.2.4
scalyr/scalyr-agent-2 pull request #1177
Opened 2023-08-14 10:03 UTC by alesnovak-s1

2023-08-14 13:29 UTC, jmakar-scalyr requested changes
These changes are ok, there just should be some more work done first

The last time I did a release I used this as a guideline (I don't know if Arthur pointed you to better/newer documentation): https://www.notion.so/sentinelone/Release-management-6c14b353ea08417fab69c58cba4c2790

Specifically I saw that the 2.2.4 CHANGELOG entry needed a "name" (and possibly more details) and more importantly that the 2.2.4 image tags have not yet been uploaded to https://hub.docker.com/r/scalyr

2023-08-14 19:59 UTC, jmakar-scalyr commented on CHANGELOG.md
> +Packaged by Ales Novak <ales.novak@sentinelone.com> on Jul 14, 2023 00:00 -0800
Should this be Aug 14?

2023-08-14 20:01 UTC, jmakar-scalyr approved these changes
Looks good
Btw I think we want to use `2.2.4` as the image tag not `v2.2.4` (ref: https://hub.docker.com/r/scalyr/scalyr-agent-docker/tags?page=1&name=2.2)

2023-08-15 06:00 UTC, alesnovak-s1 commented on CHANGELOG.md
> +Packaged by Ales Novak <ales.novak@sentinelone.com> on Jul 14, 2023 00:00 -0800
Thanks for catching that.

2023-08-15 06:26 UTC, merged